apiVersion: v1
kind: Service
metadata:
  namespace: app-namespace
  name: rust-app-service
spec:
  type: NodePort
  selector:
    app: rust-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
