apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-app-deployment
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-app
  template:
    metadata:
      labels:
        app: rust-app
    spec:
      containers:
        - name: rust-app
          image: api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:admin123@10.43.89.141:5432/info_db
